server:
    port: 8080


eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9999/eureka/


spring:
    application:
        name: wayd-gateway
    cloud:
        gateway:
            routes:
                - id: user
                  uri: lb://wayd-user
                  predicates:
                      - Path=/wayd-user/**
                  filters:
                      - StripPrefix=1